P4 = {
"Schmidtea mediterranea":
  "antique microscope field-of-view plate: ONE tiny flatworm gliding beneath the round lens over a pebble-flecked substrate, a soft pale milky leaf-shaped sliver no longer than a thumbnail, its head end broadly blunt and its tail gently tapered, a single PAIR of small dark eye-spots set close together near the head, the whole body flat as a wet leaf and smoothly ciliated at the edges, a slender pharynx faintly visible along the pale midline, a soft wash of shadow beneath — absolutely NO segments NO bristles NO round suckers NO antennae NO eyes ranged around the rim NO stripes, ink stippling, no text no letters no labels",
"Polycelis tenuis":
  "antique microscope field-of-view plate: ONE small flat dark planarian sliding across the pale circular field like a thumbnail-sized guitar pick of black felt, slender and paper-thin with a bluntly rounded head, the head's front edge set with MANY tiny pinprick eyes arranged in one continuous crescent arc — a fringe of dark dots sweeping from one side to the other — the tail drawn to a fine point, a pale narrow underside, one faint lighter stripe down the middle — absolutely NO two eyes only NO segments NO bristles NO suckers NO shell NO tail spike, ink stippling, no text no letters no labels",
"Microstomum lineare":
  "antique microscope field-of-view plate: a transparent worm seen through the round lens like a length of clear glass thread resting on a pale leaf fragment, its body utterly colourless and marked by faint cross-lines into a chain of linked zooids joined head to tail — each small segment of the chain carrying its own pair of dark eye-dots and its own tiny mouth — the chain bent gently like a loose bead necklace, fine cilia haloing the edges, one end just beginning to pinch apart — absolutely NO great black body NO arc of many eyes NO bristles NO appendages NO shell NO spots, ink stippling, no text no letters no labels",
"Clonorchis sinensis":
  "antique parasitology plate: ONE Chinese liver fluke laid flat on aged parchment like a slender translucent magnolia petal, thin as tracing paper with a narrow pointed tail end, at the front a small round oral sucker and a second slightly larger ventral sucker just behind, visible through the pale flesh the diagnostic TWO deeply branched coral-shaped testes stacked one behind the other in the hind body, a fan of coiled uterus loops filling the middle, sesame-seed-shaped brown eggs scattered beside — absolutely NO segmentation NO hooks NO long ribbon body NO head with eyes NO spiny skin, ink stippling, no text no letters no labels",
"Paragonimus westermani":
  "vintage parasitology still-life: ONE plump lung fluke resting in a shallow glass dish like a polished coffee bean or half a shelled peanut, thick-fleshed and brick-red-brown, its whole skin encrusted with tiny single-pointed scale-spines like the shagreen of a shark, a small round oral sucker at the tip and an equal-sized ventral sucker just behind on the belly, through the dense flesh the paired organs mirrored side by side, golden operculated eggs like little amber vases scattered near — absolutely NO flat leaf shape NO long ribbon NO segmentation NO hooks NO tail NO bristles, ink stippling, no text no letters no labels",
"Fasciolopsis buski":
  "antique parasitology plate: ONE giant intestinal fluke spread flat in a big porcelain dish like a sizeable slice of raw liver or a rubbery red spatula blade, remarkably large and thick-fleshed, flesh-pink to madder red, its front end bearing a tiny oral sucker immediately followed by a huge round ventral sucker several times larger — a great suction cup stamped onto the front — two deeply lobed testes ranged one behind the other down the hind body, wavy blind gut tubes flanking the midline, large pale oval eggs beside a wooden ruler — absolutely NO segmentation NO hooks NO ribbon NO bristles NO spines, ink stippling, no text no letters no labels",
"Dicrocoelium dendriticum":
  "vintage parasitology still-life: ONE lancet fluke lying on black velvet like a slender translucent glass spearhead, flat and narrowly lance-shaped with a finely pointed fore-end and a bluntly rounded rear, so transparent that its anatomy reads like a printed engraving inside — two small suckers, a pair of straight parallel gut tubes running the whole length, two rounded testes set obliquely at the middle — tiny deep-brown eggs like grains of dark sand scattered at the tip, a steel lancet needle laid alongside for scale — absolutely NO thick fleshy body NO enormous sucker NO ribbon of segments NO bristles NO spines, ink stippling, no text no letters no labels",
"Taenia saginata":
  "antique parasitology plate: a great creamy-white tapeworm ribbon coiled loosely in a museum jar like a length of satin band, at the free end its tiny squarish head — a plain knob bearing exactly FOUR round suckers and nothing else, absolutely unarmed — the ribbon widening gradually into a chain of hundreds of rectangular segments like a paper chain of postage stamps, one detached gravid segment magnified beside showing its fern-frond branched uterus, six-hooked round eggs near it — absolutely NO crown of hooks NO thorn ring NO face NO eyes NO mouth teeth NO annelid segmentation, ink stippling, no text no letters no labels",
"Echinococcus granulosus":
  "antique parasitology plate, twin studies on one sheet: above, the adult worm no bigger than a grain of rice — a thread of just THREE or FOUR segments headed by a minute knob armed with a double crown of tiny rose-thorn hooks and four round suckers; below, its larval hydatid cyst skinned open like a walnut — a translucent water-filled sac shedding brood capsules and a sediment of minute hook-crowned larval heads drifting like grains of sand — absolutely NO long ribbon body NO face NO legs NO bristles on the skin NO one solid tumour, ink stippling, no text no letters no labels",
"Echinococcus multilocularis":
  "vintage parasitology plate, twin studies: above, an even tinier adult tapeworm barely a sesame seed long, a chain of only three to five narrow segments tipped by a small hooklet-studded crown and four round suckers, the last segment a simple sack; below, its larval stage — an alveolar mass like a lump of grey-yellow beeswax gnawed into countless minute frothy vesicles, a honeycomb of tiny bubbles creeping outward and infiltrating the tissue with no single big cavity — absolutely NO one large round cyst NO long ribbon NO visible face NO legs NO hooks along the body, ink stippling, no text no letters no labels",
"Hymenolepis nana":
  "antique microscope field-of-view plate: a dwarf tapeworm uncoiled beside its eggs on one slide, the whole worm no longer than a sewing thread, its minute spherical head-knob carrying four round suckers and a retractable short proboscis fringed with ONE single ring of fine hooks, the body a simple string of broad short segments, and the diagnostic eggs — transparent near-round glassy spheres, each with a dark inner shell from whose two ends stream delicate curling polar filaments like fine hairs — absolutely NO long ribbon NO enormous suckers NO six-hooked bare egg NO face NO annelid segmentation, ink stippling, no text no letters no labels",
"Diphyllobothrium latum":
  "antique parasitology plate: a broad fish tapeworm folded in soft coils like a wide band of grey-yellow grosgrain ribbon in a museum dish, each segment distinctly WIDER than long — a band of wide short bricks — and at the end the peculiar head: a slim finger-like flattened knob bearing two long open sucking grooves, one along its back and one along its belly, instead of round suckers, one segment magnified showing its central rosette of coiled uterus like a pressed flower, ovoid eggs with one lid-end and one small knob — absolutely NO four round suckers NO crown of hooks NO square head NO segments taller than wide, ink stippling, no text no letters no labels",
"Ancylostoma duodenale":
  "vintage parasitology still-life: ONE Old World hookworm lying in a watch-glass like a piece of pale red bent wire frozen into a C-curve, slender and glassy translucent, at the head end a plump open mouth-capsule like the upturned cap of a bottle facing the viewer, its rim armed with exactly TWO PAIRS of curved hook-teeth like tiny cat's claws, a magnified head beside showing the four fangs in a ring, the male tail flared into a delicate ribbed umbrella — absolutely NO crown of plates NO big sucker disc NO segmentation NO bristles NO long whip tail, ink stippling, no text no letters no labels",
"Necator americanus":
  "antique parasitology still-life: ONE New World hookworm curled in a shallow glass dish like a soft pink S of sewing thread, more slender than its cousin, its head bent upward at the neck like a polite bow, the mouth-capsule facing forward armed not with fangs but with exactly ONE PAIR of half-moon cutting plates like two curved chisels inset in the lip, shown enlarged beside, the body pale translucent flesh-red, the male tail fanning a small ribbed umbrella — absolutely NO hook teeth NO two pairs of fangs NO segmentation NO bristles NO spiny head NO whip tail, ink stippling, no text no letters no labels",
"Meloidogyne incognita":
  "antique microscope field-of-view plate: one plant root seen through the round lens, knotted with swollen galls like beads strung on a cord, and poking from the galls the sedentary female nematodes — plump pear-shaped bodies of pearl-white like tiny teardrop pearls half-buried in the tissue — one magnified female pulled free beside, her slender neck and swollen body ending in a blunt tail, a mass of minute eggs held in a smear of jelly, a glass-clear slender male stretched nearby — absolutely NO legs NO bristles NO segmentation NO shell NO visible face NO fangs, ink stippling, no text no letters no labels",
"Ditylenchus destructor":
  "antique microscope field-of-view plate: ONE slender plant-parasitic nematode floating in the round field like a fine clear hair of glass about a millimetre long, gently bowed to one side, its transparent body ringed with hundreds of fine dense transverse annules like a tightly twisted clear rope, at the head a tiny spear-like stylet pricking forward, a round knob-like bulb visible in the throat, the tail drawn down into a smooth blunt cone, a curved spicule faint at the tail — absolutely NO legs NO bristles NO swollen pear-shaped female NO big claws NO eyes NO segmentation, ink stippling, no text no letters no labels",
"Spongilla fragilis":
  "antique freshwater natural-history plate: ONE branching crusty sponge colony resting on a stream pebble like a lump of pale-green lava foam or dried cauliflower glue, its surface knobbly with low ridges and scattered little round chimney-holes, the whole colony a surprising grass-green from algae living in its flesh, beside it a row of overwintering gemmules like tiny bronze-brown beads, and a magnified fan of glassy needle spicules with a few double-headed wheel-shaped anchors — absolutely NO coral polyps NO plant leaves NO flowers NO barrel sponge with one huge mouth, ink stippling, no text no letters no labels",
"Amphimedon queenslandica":
  "vintage sponge plate: ONE lumpy encrusting sponge cut from a reef rock, sitting on slate like a soft grey-amber loaf of bread with a craggy top, its whole skin perforated by a fine lace of countless pinprick incurrent pores while a few larger round chimney-holes pepper the summit, the flesh springy and fibrous, one corner sliced open to show the felted interior, beside a magnified bundle of slender glass needles — smooth tapering single-axis spicules crossing like pick-up-sticks — absolutely NO branching coral fan NO polyps with tentacles NO plant NO shell NO tube worms, ink stippling, no text no letters no labels",
"Halichondria okadai":
  "antique intertidal plate: ONE crumbly encrusting sponge spreading over a barnacled rock like a patch of warm melted cheddar or risen breadcrumb dough, its colour mustard yellow-brown to orange, the surface gently rolling with a few small round raised volcano-holes breathing softly, the texture spongy and fragile, a torn edge revealing the loose felt of glassy silica needles in two sizes scattered without order like spilled matchsticks beneath the lens — absolutely NO coral fan NO branching tree sponge NO polyps NO tube worms NO shell NO anemone, ink stippling, no text no letters no labels",
"Whitmania pigra":
  "antique leech still-life: ONE broad flat leech gliding across a wet china dish like a strap of dark old leather trimmed with gold piping, wide as a thumb and palm-long, its arched back olive-brown striped lengthwise by golden-yellow bands, the pale belly ruled into regular segments by deep grooves, at the head end a small round sucker mouth, at the tail a stout adhesive disc, and along the front of the back an arc of exactly FIVE PAIRS of tiny black eye-dots — absolutely NO triple saw-toothed jaws NO blood-red body colour NO branching gills NO legs NO annelid bristles, ink stippling, no text no letters no labels",
"Hirudo nipponia":
  "vintage apothecary leech plate: ONE medicinal leech stretched in a shallow ceramic cup of water like a slender ribbon of striped dark rubber, its back marked with bold lengthwise stripes of black on olive-yellow-green over a pale grey belly, the body finely ruled into close transverse rings, the front end capped by a small round sucker, beside it a magnified cutaway of the mouth showing exactly THREE semicircular saw-toothed jaw plates arranged like the spokes of a three-pointed star — absolutely NO gills NO legs NO bristles NO golden stripes NO broad flat body, ink stippling, no text no letters no labels",
"Platynereis dumerilii":
  "antique marine worm plate: ONE ragworm stretched on wet slate like a living bottle-brush, its long body built of dozens of segments, each segment swelling with a pair of fleshy leaf-shaped paddles fringed with fans of fine golden bristles like eyelash combs, the head bearing TWO PAIRS of dark eyes, a pair of short feelers and long whiplash tentacles sweeping forward, the body olive-green banded pale, and above it one ripe swimming individual with widened paddle fins and huge darkened eyes — absolutely NO centipede legs NO beetle-like antennae NO flat leech body NO shell NO suckers, ink stippling, no text no letters no labels",
"Tubifex tubifex":
  "antique microscope field-of-view plate: a dense living tangle of sludge worms packed into the round field like a nest of fine red sewing threads or a knot of blood-red vermicelli, each worm a hair-fine crimson cylinder glassy with depth, their front ends buried in dark mud while dozens of long tails rise and wave together above like a trembling meadow of red grass, faint bundles of tiny bristles just visible at each ring — absolutely NO legs NO feathery gills NO suckers NO eyes NO antennae NO flat body, ink stippling, no text no letters no labels",
}
