P2 = {
"Saccharum officinarum":
  "vintage sugar-crop botanical plate: ONE clump of three or four tall cane stalks standing like giant polished green candles two men high, each thick smooth stalk divided by pale nodes bearing a small bud at every joint, the internodes glazed with a waxy bloom and streaked wine-red where the sun has struck, long sword-like leaves with finely serrated edges arching from the crown, and one silky silver-white feather plume of flowers nodding at the very top — a cut bare stalk section lying in front shows the solid juicy pith — absolutely NO hollow bamboo joints NO hard woody trunk NO side branches NO palm fronds, ink stippling, no text no letters no labels",
"Setaria viridis":
  "antique botanical weed plate: ONE slender green foxtail grass rooted in a small clod of field soil, its stem waist-high and hair-thin with narrow rough leaves, crowned by the unmistakable cylindrical seed head like a small green cat's tail or a soft pipe-cleaner, the dense bristly spike closely fringed with short stiff whiskers, several smaller brush-heads carried on side tillers, the bristles flushing violet toward the tips, a few loose grain dots fallen below — absolutely NO showy coloured petals NO broad leaves NO woody stem NO drooping daisy flower NO wheat spear, ink stippling, no text no letters no labels",
"Brachypodium distachyon":
  "antique botanical plate: ONE small delicate annual grass no taller than a pencil, its hair-smooth slender stem topped by a digitate cluster of several slim spikes spread like the fingers of an open hand, each spike a flat two-ranked ladder of small stalkless spikelets, every floret tipped with a short straight needle-like awn, a few narrow leaves sheathing the base, and beside the plant a fusiform spindle-shaped grain showing its single shallow belly groove — absolutely NO feathery plume NO loose panicle of fine branches NO bristle whiskers like foxtail NO broad leaves, ink stippling, no text no letters no labels",
"Coix lacryma-jobi":
  "vintage botanical bead-grain plate: ONE tall leafy grass stalk beside a string of loose BEADS: the plant bears long broad ribbon leaves on a branched stalk as tall as a door, its flowering racemes strung with hard round tear-drop shaped grain-cases each the size of a large pea and shining with glazed porcelain enamel, pearly white and a few grey-brown ones, one case broken open to show the polished oval seed inside with its single lengthwise belly groove — absolutely NO wheat ear NO corncob NO clusters of soft berries NO flowers with coloured petals NO thorns, ink stippling, no text no letters no labels",
"Panicum miliaceum":
  "antique cereal-crop plate: ONE millet plant with a straight slender straw supporting a big open nodding panicle like a loose dusty mop or a small exploded firework of fine curling branchlets, each branchlet hung with strings of round shiny little seeds, a handful of husked cream-yellow and brown pearl-like grains spilled on the ground in front, narrow lance-shaped leaves with hairy bases splaying from the stalk — absolutely NO dense corn-cob ear NO wheat spear spike NO whiskery foxtail brush NO coloured petals NO spines, ink stippling, no text no letters no labels",
"Medicago truncatula":
  "vintage botanical plate: ONE small creeping hairy plant spread over dry limestone-coloured slate, its clover-like leaves each made of THREE small toothed obovate leaflets, a few little pea-flowers of soft yellow, and the signature — several seed pods each coiled into a tight flat spiral like a tiny cinnamon roll or a watch spring, two to six neat turns deep, the coil's outer rim studded with short hooked prickles like a burr, a few kidney-shaped seeds spilled from one opened coil — absolutely NO vine tendrils NO big blossoms NO long straight pod NO thorny stems, ink stippling, no text no letters no labels",
"Pisum sativum":
  "antique kitchen-garden botanical plate: ONE pea vine climbing a rustic tripod of pea-sticks, its tender hollow stem bearing pairs of blue-green oval leaflets, curling spring-like tendrils, and big leafy stipules clasping the stem like collar wings, one or two white butterfly-shaped blossoms, and the prize — plump smooth pods swollen like small green paper lanterns packed with round peas, a few shelled peas spilled beside the pot like little marbles — absolutely NO tomato fruit NO prickly spines NO woody trunk NO daisy heads, ink stippling, no text no letters no labels",
"Vicia faba":
  "vintage farm botanical plate: ONE upright broad-bean plant standing like a small green soldier, its stem sharply FOUR-ANGLED and hollow like a drinking straw, pairs of pale grey-green oval leaflets ending in weak stubby tendrils, white flowers streaked with violet veins and one ink-black blotch printed on each wing petal like an eye, thick fuzzy pods upright then drooping like small green woolly mittens, and a row of broad flat bean seeds laid out like pale buttons each marked with a single black eye — absolutely NO spiral vine NO round pea pods NO tomato NO spines, ink stippling, no text no letters no labels",
"Astragalus sinicus":
  "antique bee-pasture botanical plate: ONE low sprawling plant spread over damp paddy-field slate, its reclining stems clothed with feather-like leaves of SEVEN to THIRTEEN small pale-green obovate leaflets, from the leaf axils rise long slender bare stalks each lifting a loose head of six or eight rose-purple pea-flowers like a tiny nosegay of little bonnets, a few later sickle-curved pods tipped with a short beak, the whole herbage thinly dusted with white hairs — absolutely NO thorns NO spiny seed pods NO round clover ball NO blue flowers, one honeybee hovering, ink stippling, no text no letters no labels",
"Robinia pseudoacacia":
  "vintage dendrology plate: ONE branch cut from a black locust tree laid diagonally across parchment, bearing feather-like leaves of seven to nineteen small oval bluish-green leaflets set in two ranks, a PAIR of hard woody thorns like iron nails flanking each leaf scar, and long drooping chains of white fragrant blossoms like strings of fresh popcorn, each pea-flower wearing a small pale-yellow smudge at the base of its banner petal, a few flat dry strap-like red-brown pods twisted below — absolutely NO roses NO acorns NO round powder-puff flower balls NO palm leaves, ink stippling, no text no letters no labels",
"Capsicum annuum":
  "antique kitchen-garden plate: ONE pepper plant in a simple terracotta pot, smooth lance-shaped leaves, a single white star-shaped flower with spreading petals and a cup-shaped green calyx, and the fruit — glossy tapering pods like pieces of red lacquer carving or fat candles, some standing straight up from the branchlets, one cut lengthwise to show the hollow inner chamber and pale seeds clustered along the central white rib like beads strung on a spine — absolutely NO black peppercorns NO tomato fruit NO spines NO fuzzy peach skin, a wooden spoon of dried red pods, ink stippling, no text no letters no labels",
"Datura stramonium":
  "vintage toxic-botany plate: ONE erect rank herb as tall as a yard-stick, stout smooth pale stems, large irregularly toothed ovate leaves, one big white funnel-shaped trumpet flower more than a hand long jutting sideways from a leaf axil, and its fruits — erect egg-shaped capsules bristling all over with stout sharp spikes like medieval mace balls or green hedgehogs, one split neatly into FOUR regular valves to reveal the dark wrinkled seeds inside — absolutely NO showy colourful petals NO smooth red berries NO tendrils NO drooping pendant flowers, a wilted lower leaf curling, ink stippling, no text no letters no labels",
"Lycium barbarum":
  "antique apothecary botanical plate: ONE arching goji shrub cut and laid on parchment, its long slender branches drooping like a fountain, scattered slender thorns and narrow grey-green leaves, a few small funnel-shaped pale-lavender flowers with fringed lobes, and clusters of soft oval berries glowing scarlet-red like little jelly beans or drops of red glass, each berry wearing a tiny persistent green calyx cap, a few split open showing flat kidney-shaped seeds — absolutely NO tomato fruit NO black nightshade berries NO roses NO spiny ball fruit, a small ceramic dish of dried berries, ink stippling, no text no letters no labels",
"Solanum melongena":
  "vintage kitchen-garden botanical plate: ONE bushy eggplant sprig bearing broad fuzzy ovate leaves with wavy edges, a single large star-faced blossom of rich violet with a central boss of bright yellow anthers like a tassel, and the fruit itself — a big glossy egg-shaped berry like polished aubergine-purple porcelain or a fat varnished pendant, capped by a green star-shaped calyx whose points bear tiny prickles, one fruit halved to show the pale spongy flesh with flat seeds — absolutely NO spines all over the plant NO tomato stem NO striped melon rind NO orange pumpkin colour, ink stippling, no text no letters no labels",
"Brassica rapa":
  "antique brassica plate: ONE mustard plant with a stout flowering stem, its lower leaves large and rough with big side lobes on a winged stalk, the upper leaves clasp the stem like arrow-points, the upper third a tapering spire of small BRIGHT YELLOW flowers each made of exactly FOUR petals spread in a cross, below them long thin upright pods like slim knitting needles each finished with a pointed beak, a few round dark seeds shaken loose at the base — absolutely NO white daisy petals NO blue flowers NO tight cabbage head NO tomato, ink stippling, no text no letters no labels",
"Brassica oleracea":
  "vintage seashore botanical plate: ONE wild cabbage growing from a chalky cliff ledge, a squat unbranched stalk bearing a loose globe of thick fleshy blue-grey leaves like a giant rose carved from wax, every leaf sealed with a silvery waxy bloom and edges gently rippled like pie crust, beside it a second plant in its second year — a tall spike of little four-petaled yellow blossoms with slender beaked pods — absolutely NO purple fruit NO thorns NO orchid flowers NO tight drumhead ball of cultivated cabbage, gull feathers resting on the ledge, ink stippling, no text no letters no labels",
"Raphanus sativus":
  "antique root-crop plate: ONE uprooted radish plant shown whole with its leaves tied back, the swollen taproot like a fat polished crystal candle — a smooth white conical root flushing rose-red at the shoulder — rough hairy leaves deeply cut with big terminal lobes, beside it a second plant in flower carrying a loose head of pale lilac-white blossoms veined purple, and its curious pods strung like lumpy beads on a thread — absolutely NO long orange carrot NO potato tubers NO round cabbage head NO yellow flowers, crumbs of black soil, ink stippling, no text no letters no labels",
"Capsella bursa-pastoris":
  "vintage wayside-weed plate: ONE small pale-green herb no taller than a teacup, its base a flat rosette of feathery lobed leaves hugging the ground, a slender upright stem bearing a string of minute white four-petaled flowers at the tip while below them the stem is already strung with its signature fruits — rows of tiny flat INVERTED-TRIANGLE pods like little hearts or change-purses notched at the top, one magnified pod drawn beside the plant, fine sand grains below — absolutely NO yellow flowers NO round berries NO dandelion puffball NO thorns, ink stippling, no text no letters no labels",
"Isatis indigotica":
  "vintage dye-plant botanical plate: ONE woad plant pulled whole, a stout pale taproot like a fat ivory carrot with yellow-white skin, a much-branched stem clothed with lance-shaped leaves that clasp it like sleeves, airy sprays of tiny four-petaled yellow flowers, and the crop — clusters of flat winged pods shaped like little rounded fans or inverted teardrops with a thin papery margin all round, ripened violet-brown, beside a small bowl of indigo-blue dye pigment — absolutely NO blue flowers NO long slender pods NO thorns NO round berries, ink stippling, no text no letters no labels",
"Paphiopedilum armeniacum":
  "vintage orchid plate: ONE potted terrestrial lady's-slipper orchid with a fan of broad strap-shaped leaves tessellated like mosaic tiles in alternating light and dark green, from which rises a single short hairy stalk bearing exactly ONE great apricot-yellow blossom, its lip blown up into a plump hollow pouch like a soft leather change-purse with a curled-in mouth, two wide rounded ruffled petals spread like wings on either side of a round hood — absolutely NO spots upon the pouch NO several flowers NO aerial roots NO trumpet lily shape, a limestone pebble topping the pot, ink stippling, no text no letters no labels",
"Vanilla planifolia":
  "antique spice-plant plate: ONE vanilla vine twisting up a mossy log, its round jade-green stem jointed like bamboo cane with a tuft of white rootlets gripping the bark at each node, thick leathery canoe-shaped leaves spaced alternately, a short cluster of pale yellow-green orchid flowers with a rolled trumpet-shaped lip, and the treasure — slender drooping three-angled bean pods like long thin green pencils turning amber, one bundle of cured dark fragrant pods tied with string in the corner — absolutely NO huge showy purple orchid NO round fruit NO thorns NO succulent fleshy leaves, ink stippling, no text no letters no labels",
"Gastrodia elata":
  "antique materia-medica plate: ONE strange leafless saprophytic orchid sprouting from dark forest humus, entirely without green — a fat pale tuber like an old peeled wooden club, its surface banded with faint annular rings like stacked napkin-rings, sending up ONE chestnut-orange unbranched stalk as tall as a walking cane hung with a close spike of small pitcher-shaped ochre flowers, no leaves anywhere, a pinch of dust-fine seeds scattered beside the root — absolutely NO green leaves NO chlorophyll NO wide-open petals NO carrot-like root tuft, ink stippling, no text no letters no labels",
"Pyrus bretschneideri":
  "vintage pomology plate: ONE branch of a white-pear tree in fruit, slender often thorned twigs, glossy ovate leaves edged with fine bristle-tipped teeth, a single white five-petaled blossom tucked in the corner, and clusters of big obovoid pears hanging on stout stems like pale yellow-green porcelain bottles speckled with tiny cinnamon freckles, the blossom end clean and calyx-free, one pear halved to show the gritty stone-cell flecks around the core — absolutely NO red skin NO peach fuzz NO grape clusters NO berry bunches, ink stippling, no text no letters no labels",
"Prunus armeniaca":
  "vintage pomology plate: ONE apricot branch shown in two stages — a bare twig carrying early solitary blossoms of white blushed pink that open BEFORE any leaf appears, and a leafy twig bearing round golden-yellow fruits blushed red on the sunny cheek, each fruit wrapped in fine short velvet like a peach's little cousin, one fruit cut open beside to show the flat rough stone like a little almond-shell raft — absolutely NO smooth shiny cherry NO pointed peach tip NO clustered berry bunches NO blossoms on the leafy twig, ink stippling, no text no letters no labels",
"Fragaria × ananassa":
  "vintage kitchen-garden plate: ONE strawberry plant in a low bowl, a tuft of THREE-part leaves with coarsely toothed crowns on ribbed stalks, long runners trailing over the rim like thin strings with baby plants strung at intervals, white five-petaled blossoms with yellow centres, and ripe fruits — plump scarlet cones like sugar-dipped candy, their whole surface pocked with tiny pale-yellow seed dots, each wearing its little green leafy cap reflexed back at the shoulders — absolutely NO fruit hanging from a tree NO purple flesh NO long spiked crown NO fuzzy skin, ink stippling, no text no letters no labels",
"Eriobotrya japonica":
  "antique fruit-tree plate: ONE loquat branch heavy with clusters of round apricot-gold fruits like small dim suns, their skins dusted with soft russet velvet and tipped with the black remnant of the stigma, the sturdy leathery spear-shaped leaves shown from both faces — lacquered deep green above, felted rusty-brown beneath like suede — and at the branch tip a foamy cluster of small creamy-white flowers breaking from woolly buds — absolutely NO long thin pods NO thorns NO fuzzy yellow peach NO cone-shaped fruit, ink stippling, no text no letters no labels",
"Hevea brasiliensis":
  "vintage plantation plate: ONE rubber tree shown as a tall pale-barked trunk scarred by a herringbone lattice of tapping cuts with a small cup of milky white latex hung beneath, its crown of leaves each a THREE-fingered green hand on a long stalk, and on a side branch the fruits — small round wooden capsules splitting cleanly into THREE valves that curl back like umbrella ribs to fling out mottled brown seeds, one seed cut to show the white kernel — absolutely NO winged maple seeds NO big showy blossoms NO spines NO palm fronds, ink stippling, no text no letters no labels",
}
