P1 = {
"Mustela nivalis":
  "antique mammalogy plate on aged parchment: TWO small weasel pelts laid side by side like a pair of slim velvet glove-fingers, each one slender tapered living tube no longer than a hand, one in chestnut-brown summer fur with pure white underparts, the other in full winter ermine-white, both keeping exactly ONE small jet-black tip on the short stubby tail, tiny rounded ears, bright black bead eyes, little white paws, a narrow inquisitive muzzle — absolutely NO long bushy fox tail NO stripes NO spots NO big paws NO snow landscape, simple warm grey slate ground, ink stippling, no text no letters no labels",
"Nyctereutes procyonoides":
  "vintage natural history plate: ONE stocky low-slung raccoon dog standing on warm grey slate like a small brown bear rug given legs, long shaggy grey-brown fur thick from crown to rump, unmistakably short black-brown legs, a dark hairy mask drawn across the eyes with long puffy cheek ruffs like a scarf, small rounded ears, and a short drooping bushy tail finished in a plain dark tip — the tail is one solid unbroken colour — absolutely NO ring-striped raccoon tail NO white face NO slim fox legs NO bright tawny coat, a few grass stems on the ground, ink stippling, no text no letters no labels",
"Rhabdophis tigrinus":
  "antique herpetology plate: ONE loose coil of emerald garden hose laid on pale slate — the hose is really a snake with a smooth oval head, large eyes with round pupils, a back of bright green scattered with bold black blotches, strongly keeled ridged scales catching the light like woven cord, and a plain pale yellow-white underside, the thick neck shown slightly inflated where two parallel groove-glands bulge along its nape as it rears in defence — absolutely NO triangular viper head NO heat-sensing pit NO vertical slit pupils NO rattle NO spreading hood, one shed skin curling at the frame edge, ink stippling, no text no letters no labels",
"Protobothrops mangshanensis":
  "vintage venomous-serpent plate: ONE thick heavy viper coiled like a moss-green ship's rope on dark slate, its deep bottle-green body overlaid with an irregular network of yellowish-tan markings like bronze wire mesh wrapped around the rope, a big triangular flat head with an upturned pointed snout, one small heat-pit between eye and nostril, vertical slit pupils, pale yellow-white belly speckled with fine black dots, and the very tail tip drawn out in bright yellow-white like a pale wax taper — absolutely NO smooth python skin NO coral-snake bands NO spreading hood NO rattle, moss and a wet stone at the frame edge, ink stippling, no text no letters no labels",
"Vipera berus":
  "antique European serpent plate: ONE short stout adder coiled in a loose spiral like a thick plaited leather strap on heather-tinted slate, its back carrying the unmistakable bold black ZIGZAG ribbon running from neck to tail like a row of linked chevrons, ground colour warm copper-grey with strongly keeled rough scales, a small flat head covered in tiny granular scales instead of large plates, smallish eyes with glowing copper-red irises and vertical slit pupils, a short blunt tail — absolutely NO smooth glossy python skin NO rounded blunt head NO ear-like horns NO rattle, a sprig of heather beside the coil, ink stippling, no text no letters no labels",
"Deinagkistrodon acutus":
  "antique herpetology plate: ONE long brown pit-viper coiled on grey slate like a broad old leather belt stamped at even intervals with a single row of dark diamond lozenges, the belt ending in a large triangular arrowhead with a sharply upturned pointed snout like the tip of a silver shoehorn, symmetric large shields covering the crown, one deep heat-pit between nostril and eye, a vertical slit pupil, chalk-white underside edged with dark smudges, and a thin horny spine capping the short tail — absolutely NO coral-snake bands NO rattle NO spreading hood NO huge bared fangs, a fern frond shadow across the slate, ink stippling, no text no letters no labels",
"Pogona vitticeps":
  "vintage reptile plate: ONE laterally flattened lizard standing tall on red desert sandstone like a grey-brown leather jerkin studded with tiny thorns, its body pressed thin from the sides like a well-worn book cover, a broad triangular head with a large round exposed eardrum, neat rows of small sharp spikes fringing the throat and neck flanks like a ruff of nail heads, the chin pouch puffed and inked deep BLACK as its namesake beard, stubby strong legs, and a long tapering tail ringed with bands of small spines — absolutely NO tall sail-fin crest NO wing membranes NO devil horns NO dewlap flap NO green iguana colour, ink stippling, no text no letters no labels",
"Iguana iguana":
  "antique naturalist's plate: ONE large arboreal lizard sprawled along a mossy branch like a sculpture cut from soft green leather, a very long banded tail longer than the whole body trailing behind, a crest of tall upright soft spikes running from the nape down the spine onto the tail like the teeth of a saw, one big round white scale at each jaw corner like a porcelain button, a large drooping flap of dewlap skin beneath the chin, robust sprawled limbs with longer hind legs and a prominent eardrum — absolutely NO spikes upon the head NO umbrella frill NO horned nose NO turquoise blue colour NO fat round body, ink stippling, no text no letters no labels",
"Mauremys reevesii":
  "vintage chelonian plate: ONE small pond turtle posed beside a shallow water dish on pale slate, its carapace a low smooth oval dome like a polished brown wooden bread-board carrying exactly THREE blunt lengthwise ridges from front to back, a pale yellow-brown plastron patterned with a few big dark blotches, flat broad paddle limbs with webbed toes — front feet FIVE claws, hind feet FOUR — thin yellow-green pinstripes along the wrinkled neck, small bright eyes on a smooth olive head — absolutely NO red ear patch NO hooked snapping beak NO sea-turtle flippers NO soft leathery shell, ink stippling, no text no letters no labels",
"Pelochelys cantorii":
  "antique river-monster still-life: ONE colossal softshell turtle resting like a huge deflated grey-brown leather sandbag on a sandy riverbank tray, its carapace entirely sheathed in smooth soft skin with no scutes, a broad thick fleshy skirt flaring around the rim like the rolled edge of pie crust, a very short and extremely broad blunt snout on a frog-like head with small close-set eyes, a powerful thick neck, flat fully webbed paddle limbs — absolutely NO horny shell plates NO long snorkel proboscis NO pointed nose NO stripes NO eagle talons, a few river pebbles and a driftwood stick, ink stippling, no text no letters no labels",
"Testudo horsfieldii":
  "antique chelonian plate: ONE small round-domed tortoise on dry loess-coloured slate, its carapace a smooth sandy yellow-brown dome patterned with scattered dark smudges like an old glazed bun, the feet of the stout scaly legs ending in exactly FOUR blunt claws on every foot — count them, four toes on each front foot and four on each hind foot — thick forearms built like little shovels for digging, a scaled head with a bright dark eye, a very short tail, the compact body drawn half-tucked against the shell — absolutely NO five-toed feet NO webbed paddles NO tall spiked shell NO hinged plastron, ink stippling, no text no letters no labels",
"Echinotriton chinhaiensis":
  "vintage herpetology plate: ONE stout stocky newt posed on wet mossy slate like a liquorice sweet with an orange filling, its flat thick body and broad round-snouted head all in deep black-brown, the underside glowing orange-yellow as if painted on the belly and around the vent, a single neat row of small round warty bumps along each flank from shoulder to hip, a moderately flattened tapering tail shorter than the body, four short stubby legs splayed in a slow walk — absolutely NO tall sail-fin crest NO feathery gills NO green skin NO long whip tail NO webbed frog feet, one wet leaf beneath, ink stippling, no text no letters no labels",
"Salamandra salamandra":
  "antique natural history plate: ONE portly fire salamander striding over charcoal-grey slate, its whole glossy jet-black body splashed with bold irregular chrome-yellow patches like drops of bright paint on a charred log, a broad flat head with two large protruding eyes and a pair of swollen parotoid glands bulging behind the skull, thick raised glandular ridges along the spine, short sturdy legs — front feet FOUR toes, hind feet FIVE — and a round cylindrical tail — absolutely NO green tree-frog skin NO giant fin crest NO feathery larval gills on this adult NO spikes, a fallen beech leaf beside, ink stippling, no text no letters no labels",
"Hoplobatrachus rugulosus":
  "vintage batrachian plate: ONE big beefy tiger frog sitting alert on paddy-mud slate like a plump olive-brown leather purse, its thick back scored with several long raised skin ridges running lengthwise between bold dark tiger-like cross-bars, a pointed snout, a very large round eardrum disc behind each eye, a loose pale pouch of throat skin, chalk-white belly, and powerfully muscled hind legs with nearly fully webbed toes — absolutely NO bright leaf-green colour NO sticky toe pads NO warty toad skin NO red eyes NO tadpole tail, a few rice seedlings sprouting at the edge, ink stippling, no text no letters no labels",
"Quasipaa spinosa":
  "antique stream-frog plate: ONE chunky brown frog perched on a wet boulder beside a mountain brook, its back the colour of burnt toast scattered with dark rough warts like a stale loaf rolled in gravel, no visible eardrum, blunt rounded fingertips, and the tell-tale mark of the male — chest and belly armoured with a dense field of tiny black thorn-spines like a bed of small nails — thick powerful hind limbs gripping the slick rock, webs stretched between the toes — absolutely NO bright green skin NO round toe suction discs NO inflated vocal bubble NO tiger stripes, water splashing at the stone edge, ink stippling, no text no letters no labels",
"Hyla arborea":
  "vintage tree-frog plate: ONE tiny gem-green frog no bigger than a grape clambering up a slender reed stem, its smooth bright leaf-green back and plump round gumdrop body, a bold chocolate-brown stripe running from the snout through the eye and down each flank to the hip, cream-white belly, fingers FOUR and toes FIVE, every digit ending in a neat round sticky pad like a tiny suction cup, large golden eyes with horizontal pupils, and a male's loose pale throat skin puffed into a small translucent bubble — absolutely NO brown warty toad skin NO red eyes NO fully webbed swimming feet NO claws, ink stippling, no text no letters no labels",
}
