P7 = {
"Cornu aspersum":
  "vintage conchology plate: ONE brown garden snail crawling over a mossy brick, its shell a slightly squashed globe of polished horn about the size of a walnut, four to five swelling whorls banded with several dark chocolate spiral stripes over amber-brown and engraved with fine growth wrinkles, the crescent-shaped mouth edged by a white gently rolled lip, a grey-brown body with FOUR head-tentacles — the long upper pair tipped with round dark eyes, the short lower pair like small feelers — absolutely NO flat coiled disc shell NO horny operculum lid NO stripes painted on the flesh NO naked slug, ink stippling, no text no letters no labels",
"Bradybaena ravida":
  "antique garden-weed plate: ONE plump land snail posed on damp soil beside a crumbled leaf, its shell a small depressed globe like a polished brown leather button of five to six gently swelling whorls, the surface dusty grey-yellow-brown etched with fine growth lines like fingerprints pressed in clay, a simple oval mouth without a thickened lip, a narrow slit umbilicus half-hidden, the soft grey-brown body bearing two dark-tipped tall eye-stalks and two short lower feelers — absolutely NO bold dark spiral bands NO chalk-white thick lip NO flat coiled disc NO bright banded colouring, ink stippling, no text no letters no labels",
"Bradybaena similaris":
  "vintage micro-landsnail plate: ONE small conical land snail on a lichen-dusted stone, its shell a low rounded turret of five to six slowly widening whorls like a spinning-top turned from polished amber, the yellow-brown surface softly variable, the tilted oval mouth simple on its outer rim but marked along the inner lip by a dark chestnut callus rib like a stroke of lacquer — the species' signature — the soft body bearing two pairs of tentacles with dark eyes on the tips of the tall rear pair — absolutely NO strong spiral stripes NO white rolled lip NO flat coiled disc NO spiny ribs NO horny lid, ink stippling, no text no letters no labels",
"Limacus flavus":
  "antique cellar-naturalist plate: ONE large shell-less yellow slug stretched across an old damp flagstone like a roll of apricot toffee, its soft yellow-brown back freckled and striped with slate-blue-black spots and lengthwise dashes, a distinct raised keel running down the midline of its tail-end like the ridge along a loaf, TWO PAIRS of head tentacles — the upper pair bearing eye-tips — a round breathing pore opening on the right side near the head, a glistening smear of yellow slime marking its wake — absolutely NO shell NO spiral house NO tiger stripes NO blue skin NO snail, ink stippling, no text no letters no labels",
"Bellamya aeruginosa":
  "vintage freshwater plate: ONE viviparous snail crawling on sandy pond mud, its heavy shell a stout little pagoda of six to seven flat-topped storeys with deep suture grooves, the ground colour dull jade-green overlaid with rings of verdigris copper-rust encircling each storey like tarnished bracelets, fine lengthwise rib-scratches crossing the surface, a big final whorl carrying the oval mouth sealed by a thin horny operculum door — absolutely NO glossy marine cone NO long coral spines NO red-white bands NO flat coiled disc NO stripes on the flesh, ink stippling, no text no letters no labels",
"Haliotis diversicolor":
  "vintage conchology plate, NOT a spiral whelk: ONE ear-shaped flat low oval abalone shell resting beside its broad muscular foot, the exterior brick-red to reddish-brown roughened with small warty bumps and fine spiral thread-ribs, along one margin a single neat row of exactly SEVEN to NINE raised open pore-holes spaced like buttonholes, paired with a second specimen tilted to reveal the whole interior paved in shimmering rainbow nacre — absolutely NO pointed spiral spire NO twisted whorl coils NO round moon-snail shape NO long spines NO ribbed scallop fan, ink stippling, no text no letters no labels",
"Cypraea tigris":
  "antique conchology plate: ONE tiger cowrie on black velvet like a heavy porcelain egg painted with big dark rosette spots of blackish brown scattered over a glazed milk-white ground, its swollen-oval shape slightly pinched at each end, the underside bearing one long narrow slot-shaped mouth fringed with rows of fine comb-teeth along both lips, and beside it the living animal — a soft mantle of grey flesh drawn up over the shell's back, studded with branching finger-like papillae like a thicket of tiny trees — absolutely NO spiral spire NO pointed cone NO stepped whorls NO zebra stripes NO letters, ink stippling, no text no letters no labels",
"Mauritia arabica":
  "antique conchology plate: ONE Arabian cowrie resting on sand-coloured velvet like a swollen porcelain cushion, its glossy chestnut-brown back densely veined with fine wavy cream lines that ripple and interlace like wind-blown brush strokes across the shell, interrupted here and there by small dark eye-dots, the underside pale with a long narrow slot-mouth edged by fine comb-teeth ridges, the inner lip face glazed porcelain-white — absolutely NO real letters NO words NO numerals NO spiral spire NO round rosette spots like a tiger cowrie NO zebra stripes, ink stippling, no text no letters no labels",
"Cassis cornuta":
  "vintage conchology plate: ONE great helmet shell on dark velvet like an ivory crown carved for a giant, its vast swollen body whorl set at the shoulder with a ring of stout blunt HORNS — big knobbed tubercles marching around the crown rim — the low spire almost buried at the apex, the grey-cream surface corded with coarse spiral ribs stained coffee-brown in the hollows, and below the long narrow mouth whose outer lip flares out thick and glossy, its inner edge toothed like a comb — absolutely NO long spiral trumpet shape NO thin spikes everywhere NO tiger spots NO cowrie egg-shape NO zebra stripes, ink stippling, no text no letters no labels",
"Charonia tritonis":
  "antique conchology plate: ONE giant trumpet triton on slate like a monumental spiral hunting horn, its heavy spindle-shaped shell as long as a forearm, the whorls swelling in a grand staircase spire, the cream-white surface checkered with bold chestnut blotches and corded with coarse spiral ridges, a wide oval mouth lined with porcelain-white enamel and a thick flaring outer lip rolled outward, the base drawn out into a long open front canal like a trumpet's mouthpiece end — absolutely NO crown of horns NO cowrie egg-shape NO thumbnail-size shell NO flat coiled disc NO spines, ink stippling, no text no letters no labels",
"Nassarius succinctus":
  "vintage conchology plate: a small cluster of three nassa shells on grey slate, each no longer than a thumbnail, shaped like a plump little spindle — the body whorl big and round with small spire steps above — the cream-yellow ground banded with crisp red-brown spiral stripes like skeins of thread wound on a bobbin, crossed by fine riblets, a small toothed doorway within the oval mouth and a tiny short canal notch at the base, a thin brown horny operculum lying beside one — absolutely NO giant trumpet NO crown of thorns NO zebra stripes NO long sword-like canal NO cowrie egg-shape, ink stippling, no text no letters no labels",
"Conus textile":
  "antique conchology plate: ONE textile cone on black velvet like a porcelain spindle wrapped in brocade, its glossy milk-white ground veiled with a fine brown netted pattern of tiny tents and zigzags, overlaid by exactly THREE broad transverse dark bands sweeping from crown to tip, the spire remarkably LOW and flat-topped rather than a tall tower, a long narrow slot mouth with porcelain-white interior and a perfectly smooth lip, beside it a magnified translucent harpoon tooth barbed at its tip — absolutely NO tall pointed spire NO knobbly shoulder tubercles NO tiger cowrie spots NO simple stripes only NO letters, ink stippling, no text no letters no labels",
"Aplysia californica":
  "vintage marine laboratory still-life: ONE California sea hare resting in a shallow glass tank of kelp like a plump soft sculpture of reddish-brown wax, its large loose body freckled with darker spots, a front pair of small tubular head-stalks and behind them the tall rear pair standing up like a rabbit's ears — the rhinophores — broad flaps of side skin winging outward from the shoulders almost meeting over the back, a swirl of deep purple ink blooming from its rear into the clear water, no shell visible — absolutely NO snail shell NO fish fins NO octopus arms NO rabbit face NO claws, ink stippling, no text no letters no labels",
"Mimachlamys nobilis":
  "antique conchology plate: ONE noble scallop opened flat on slate like a lady's folding fan, the left valve deep purple-brown with bold radial ribs edged in upturned scales like rows of small thorny combs, the right valve chalky-cream, both valves bearing little squarish ears flanking the hinge, the interior nacre flushed peach-pink, the great round central adductor muscle shown like a pale medallion of wax, a few silky byssus threads anchoring the hinge corner — absolutely NO oyster lumps NO spiral snail NO mussel banana-shape NO smooth featureless valves NO thorns all over, ink stippling, no text no letters no labels",
"Ruditapes philippinarum":
  "vintage seafood still-life: a small heap of Manila clams on a wooden market board, each shell a sturdy little oval biscuit the size of a walnut with its beaks bent toward the front end, the cream to russet-brown surface chequered — concentric growth rings woven across by finer radial ribs into a delicate lattice like basket-work — the inner faces porcelain-white with three little cardinal teeth below each beak, one shell gaping to show the pale axe-shaped foot and two slender separate siphons — absolutely NO spiral snail NO scallop fan-ribs NO mussel wedge-shape NO oyster lumps NO spines, ink stippling, no text no letters no labels",
"Sinonovacula constricta":
  "antique mudflat market plate: ONE razor clam propped upright in wet grey mud beside its opened pair of shells, the shell a slender straight oblong case like the handle of an old cut-throat razor, thin and chalk-fragile, its beaks set right at the front end with the rear gape slightly ajar, the outside glazed pale yellow-brown with fine concentric growth lines and a thin horny skin peeling at the edges, the fat white axe-shaped foot thrust downward and two long separate rubbery siphons reaching up like periscope tubes — absolutely NO spiral shell NO scallop fan NO round clam NO oyster lumps NO spines, ink stippling, no text no letters no labels",
"Pinctada maxima":
  "vintage pearl-fishery plate: ONE great pearl oyster standing ajar on slate like an immense ear of overlapping roof-shingles, its oblique oval shell nearly as wide as a dinner plate, the outside brown and rough with rows of upturned scaly tiles, the dorsal hinge line straight and long, while the inside is a treasury — thick lustrous nacre flooding the interior with silver and rose iridescence, the curling lip of the margin glowing a soft GOLD, a single round pearl resting in the cup — absolutely NO scallop fan-ribs NO spiral snail NO mussel wedge-shape NO concentric clam rings NO spines, ink stippling, no text no letters no labels",
"Cristaria plicata":
  "antique river-fishery plate: ONE large freshwater mussel lying valve-down on wet slate like a soft brown leather carry-bag, its thin inflated shell stretched long, the hind upper edge lifted and spread into a broad pleated WING — a thin triangular crown creased with folds like the crimped edge of a pastry — the yellow-brown surface rough with growth rings like bark, the pearly interior milky with a faint iridescence, and in a corner circle a tiny hooked glochidium larva magnified — absolutely NO gold pearl-oyster lip NO scallop ribs NO spiral snail NO spines NO rounded marine clam shape, ink stippling, no text no letters no labels",
"Perna viridis":
  "vintage harbour still-life: a clustered bouquet of green mussels hanging by dense byssus threads from the frayed end of a rope, each shell a smooth elongate wedge like an emerald-enamelled banana with its pointed beak at the top, the glossy jade-green surface ruled with fine concentric growth lines, the straight back edge and broadly curved belly edge gaping slightly to show pale meat and the vivid green inner rim, dark golden-brown byssus fibres gripping the rope — absolutely NO scallop fan NO oyster lumps NO spiral snail NO pearl cup NO spines NO blue-black colour, ink stippling, no text no letters no labels",
"Crassostrea hongkongensis":
  "antique oyster-farm still-life: ONE Hong Kong oyster presented valve-open on a wooden hatchery board like a rough stone soup-bowl with its flat porcelain lid held ajar, the lower valve deeply cupped and cemented to a rock stub, the upper valve a simple flat cap, both flounced on the outside with grey-brown scale-folds like crumpled laundry, the interior china-white with one big dark muscle scar stamped behind the middle, the fleshy body pearly-white rimmed by a fringed black mantle skirt — absolutely NO scallop ribs NO green mussel wedge NO spiral snail NO pearl on display NO spines, ink stippling, no text no letters no labels",
}
