P5 = {
"Penaeus monodon":
  "vintage seafood still-life: ONE giant tiger prawn laid on crushed ice like a curved plank of dark lacquered wood banded with pale stripes, a long serrated sabre-like rostrum rising from the head with an upturned tip, stalked eyes, sweeping antennae, five pairs of walking legs ringed alternately blue and yellow like beaded jewellery, a broad fan of tail uropods and a spear-pointed telson, dark shell plates banded cream — absolutely NO big heavy claws NO flat crab carapace NO lobster armour NO bright red cooked colour NO net-like web, ice chips scattered around, ink stippling, no text no letters no labels",
"Exopalaemon carinicauda":
  "antique fish-market plate: ONE small ridgetail white prawn curled on wet blue slate like a figurine spun from frosted glass, its thin shell porcelain-white and faintly translucent dusted with sparse rust-red freckles, a fine needle rostrum arching up from the brow, the tail's pointed telson raised into a keeled ridge like the ridge-line of a little rooftop, slim transparent legs with the second pair tipped by tweezer-tiny pincers, a spread fan of fine swimmerets — absolutely NO huge claws NO tiger stripes NO spiny lobster armour NO flat crab body, water droplets on slate, ink stippling, no text no letters no labels",
"Oratosquilla oratoria":
  "vintage crustacea plate: ONE mantis shrimp stretched on wet slate like a sleek flattened torpedo of grey-green glass, its short loose carapace followed by a long roomy segmented abdomen banded with pale yellow-brown cross-stripes, a broad tail fan spread open like a folded paper fan, two enormous independently swivelling dome eyes on stalks, and folded beneath the mouth the signature weapon — a pair of sickle-shaped striking arms like folded jack-knives edged with a comb of small sharp spines — absolutely NO big round lobster claws NO serrated shrimp rostrum NO crab legs NO feathery gills NO fish fins, ink stippling, no text no letters no labels",
"Portunus pelagicus":
  "antique crab still-life: ONE male blue swimmer crab posed on white sand like a porcelain dish brushed with indigo, its broad spindle-shaped shell finely speckled, the front rim cut into exactly FOUR sharp teeth between the eyes, long slender claws spotted with blue-violet on white, eight pointed walking legs, and the last pair of legs transformed into flat oval swimming paddles like little oars, beneath a pale belly and a narrow pointed apron — absolutely NO nine marginal teeth NO red rock-crab colour NO rounded pebble carapace NO hairy legs NO giant mud-crab claws, ink stippling, no text no letters no labels",
"Portunus sanguinolentus":
  "vintage crab plate: ONE blood-spotted swimming crab resting on pale slate like a smooth sand-coloured saucer, its finely granular carapace bearing the unmistakable badge — exactly THREE round blood-red spots arranged in a neat arc across the back — strong robust claws with rough granular palms, eight pointed walking legs, and the final pair of legs flattened into swimming paddles like narrow wooden spoons, small eyes on short stalks at the pointed front — absolutely NO blue-purple spots NO four frontal spines NO giant rounded carapace NO hairy legs, a scatter of broken shells, ink stippling, no text no letters no labels",
"Charybdis feriata":
  "antique crab still-life: ONE large crucifix crab posed on dark slate like a plate of old ivory porcelain crazed with a net of red-brown crackle, its smooth shell divided into raised map-like regions, a bold rust-coloured band stamped between the eyes, the front edge cut into exactly SIX blunt teeth, thick heavy claws bearing strong teeth along the inner edge of each forearm, and the hindmost pair of legs again flattened into oval paddles — absolutely NO three red spots NO blue-purple spots NO hairy body NO rounded dome like stone crab NO nine side teeth, ink stippling, no text no letters no labels",
"Scylla paramamosain":
  "vintage estuary still-life: ONE mighty mud crab standing on grey estuarine mud like a broad shield of green porcelain, its smooth olive-green carapace edged with about nine teeth along each side rim and the front edge between the eyes cut into exactly FOUR rounded lobes, a pair of crushing claws — one heavier than the other — with massive swollen palms, pointed stout walking legs, the fourth pair flattened into paddles fringed with bristle oars — absolutely NO red spots NO net-like crackle patterns NO long spiny rostrum NO hairy legs NO blue colour, rivulets of mud water, ink stippling, no text no letters no labels",
"Cherax quadricarinatus":
  "antique aquarium plate: ONE redclaw crayfish posed on river gravel like a sculpture of blue-green lacquer, its smooth oval shell grading from teal to olive, a straight slender serrated spear-like rostrum, long elegant claws — each joint's outer face glowing with a blotch of scarlet-red like a wax-seal stamp, larger on the male — four pairs of fine walking legs, a broad plated tail fan half-spread, long white feelers sweeping forward over the eyes — absolutely NO marine lobster's heavy armour NO knobbly giant claws NO spotted crab shell NO paddle-only legs NO bright red body, ink stippling, no text no letters no labels",
"Amphibalanus amphitrite":
  "antique fouling-organism plate: a cluster of small acorn barnacles cemented to a weathered ship timber like a group of tiny grey-white volcano cones, each about the width of a fingernail, the conical little shell built of six fused wall plates tinged with purple, the summit closed by a diamond-shaped trapdoor of paired valves striped with purple, one barnacle magnified beside with its lid open and six pairs of feathery purple cirri unfurled like a bouquet of tiny plumes sieving the water — absolutely NO spiral snail shell NO worm tubes NO crab legs NO mussel shape NO anemone petals, ink stippling, no text no letters no labels",
"Chthamalus challengeri":
  "vintage tide-zone plate: a crowded pavement of tiny chalk-white barnacles crusting a sun-baked sea rock like a field of pale peppercorn domes, each little shell barely a few millimetres wide, low and rounded with six fused wall plates faintly rosy, every minute summit shut tight by a neat diamond-shaped opercular door against the drying air, one corner of the rock shown awash with small feathery cirri nets combing the water — absolutely NO tall volcano cones NO spiral shells NO worm tubes NO anemone tentacles NO crab shape, ink stippling, no text no letters no labels",
"Calanus finmarchicus":
  "antique microscope field-of-view plate: ONE planktonic copepod drifting in the round lens field like a tiny transparent grain of rice trailing two long antennae, its plump oval fore-body cleanly jointed away from the slim narrow tail-piece, the first pair of antennae extraordinarily long — reaching back past the tail like a pair of slender stilts — a minute abdomen ending in short bristled rami, fine plumose swimming legs fanned beneath, the whole body glass-clear with a soft oil-blue blush in the middle — absolutely NO big dark compound eyes NO pair of hanging egg sacs NO barnacle shell NO crab shape NO insect legs, ink stippling, no text no letters no labels",
"Cyclops vicinus":
  "antique microscope field-of-view plate: ONE female cyclops copepod treading water in the round field like a transparent teardrop wearing saddlebags, her plump oval front body and narrow jointed rear, a single small RED median eye glowing like a tiny garnet at the top of the head, short front antennae, short tail branches spreading fine feathered bristles, and TWO round clutches of pale eggs hanging like twin pendant pearl-bags at her waist, the body glassy with a whisper of yellow-green — absolutely NO antennae longer than the body NO pair of large black eyes NO shell carapace NO insect legs NO worm shape, ink stippling, no text no letters no labels",
}
