P6 = {
"Heteropoda venatoria":
  "vintage household-naturalist plate: ONE large huntsman spider flattened against a shadowed wall corner like a hand-sized patch of tan leather given legs, all eight long limbs stretched SIDEWAYS in crab fashion, banded with dark knee-rings and bristled like pipe cleaners, the flat brown body bearing a bold WHITE band stamped across the front edge of the head above the jaws, a cluster of eight eyes with the middle rear pair conspicuously enlarged and gleaming, a pale chevron pattern along the oval abdomen — absolutely NO spider web NO round orb NO tarantula bulk NO red hourglass NO violin mark, ink stippling, no text no letters no labels",
"Agelena labyrinthica":
  "antique meadow plate: ONE labyrinth spider posed at the throat of its great funnel web spread across the grass like a silken handkerchief drawn into a woolly funnel-tube, the spider itself slim and grey-brown with TWO bold dark racing stripes running down the carapace, eight eyes in two neat rows, its most striking feature — the long two-jointed posterior spinnerets sticking out behind the abdomen like a pair of little tail pipes — slender banded legs held taut, ready to bolt down the funnel — absolutely NO orb wheel web NO crab-sideways stance NO white head band NO tarantula hair NO red markings, ink stippling, no text no letters no labels",
"Misumenops tricuspidatus":
  "vintage flower plate: ONE tiny crab spider lurking on the golden face of a daisy like a living pistil, the female grass-green to creamy-yellow with a smooth pear-shaped abdomen hinting a faint pair of crimson marks on its back, her FIRST TWO PAIRS of legs stretched out sideways like arms opened for an embrace while the rear pairs sit short, all eight tiny eyes in two curved rows above the jaws, a smaller male visitor below wearing dark red lengthwise stripes — absolutely NO spider web NO orb NO long spindle legs NO brown house-spider body NO red hourglass, ink stippling, no text no letters no labels",
"Lycosa singoriensis":
  "antique steppe plate: ONE big burrowing wolf spider crouched at the rim of its silk-lined earthen burrow like a fist-sized lump of brown velvet, her arched head-shield painted with a pale median stripe and radiating dark rays, EIGHT shiny pearls of eyes arranged in three rows with the bottom four biggest, thick furry legs ready to sprint, stout jaws thrust forward with curved fangs folded like cat-claws, a neat round silk-hinged trapdoor of soil lying open beside the hole — absolutely NO orb web NO funnel sheet NO red hourglass NO violin marking NO crab stance, ink stippling, no text no letters no labels",
"Pardosa pseudoannulata":
  "vintage rice-paddy plate: ONE small wolf spider sprinting across a wet paddy stone like a bead of brown jade ringed for racing, her low carapace bearing a pale T-shaped blaze on top, the oval abdomen stamped with a dark spear-head mark ringed by yellow-white curlicues, legs banded black-and-white like striped socks, four large gleaming rear eyes catching the light, and — her badge of motherhood — a round WHITE silk egg-ball hitched firmly beneath her tail, carried wherever she runs — absolutely NO web of any kind NO crab-sideways legs NO red hourglass NO orb, ink stippling, no text no letters no labels",
"Hylyphantes graminicola":
  "antique microscope field-of-view plate: a miniature scene under the lens — a sheet-web spider no bigger than a peppercorn waiting beneath its tiny horizontal hammock of silk spread between two grass stems, a loose tangle of irregular support threads arched ABOVE the sheet like a shroud of mist, the little male polished blue-black with slim pale legs and an oval satin abdomen, fine hairs catching the light, a duller umber female lurking at the web's edge beneath a curled leaf — absolutely NO orb wheel web NO funnel tube NO large spider NO striped legs NO red marks, ink stippling, no text no letters no labels",
"Plexippus paykulli":
  "vintage courtyard plate: ONE bold jumping spider posed on a sun-warmed brick wall like a little black racing car with white pinstripes, the male's jet-black head-shield and abdomen each crossed by a neat WHITE longitudinal band, a broad blunt front face dominated by two enormous round anterior eyes like headlights flanked by smaller side eyes, sturdy legs with dense tufted feet that grip sheer glass, a single fine safety thread of silk trailing behind from a recent leap — absolutely NO orb web NO funnel NO crab-leg sprawl NO red hourglass NO tarantula hair, ink stippling, no text no letters no labels",
"Pandinus imperator":
  "antique terrarium plate: ONE emperor scorpion rearing in a defensive crescent on the rainforest floor like a carved idol of black lacquer, its glossy granular body and fat tail segments all jet black, the tail held in a high tight curve ending in a round bulbous venom sac tipped by a surprisingly SMALL sting, its forelimbs the glory — a pair of massive red-brown pincers like two leather boxing gloves on strong arms, four pairs of stout marching legs, tiny dark eyes set above the armour — absolutely NO thin whip tail NO huge exaggerated sting NO bright yellow colour NO wings NO crab shape, ink stippling, no text no letters no labels",
"Sarcoptes scabiei":
  "antique microscope field-of-view plate: ONE itch mite filling the round lens field like a minute milky-white tortoise seen from above, its plump hemispherical back tattooed with dense wavy transverse ridges studded with rows of small triangular spines, FOUR PAIRS of short stubby legs projecting from the corners — the front two pairs tipped with long-stalked round suction pads on thin stems, the rear two pairs ending in long trailing bristles — the mite burrowing into a pale tunnel of flaked skin along the frame — absolutely NO eight long legs NO large eyes NO antennae NO insect wings NO worm body, ink stippling, no text no letters no labels",
"Dermatophagoides pteronyssinus":
  "antique microscope field-of-view plate: ONE plump house-dust mite centred in the round field like a translucent milky jellybean seen hugely magnified, its soft elongate-oval body ringed with fine wrinkled transverse striations like the folds of a deflated balloon, sparse long fine hairs rising from the rounded back, a tiny head end with feeble little mouthparts merged into the front, FOUR PAIRS of short chubby legs each ending in a small round pad, dust flakes and fabric fibres drifted around it — absolutely NO long spider legs NO wings NO antennae NO segmented worm body NO shell carapace, ink stippling, no text no letters no labels",
"Phytoseiulus persimilis":
  "vintage greenhouse plate under the lens: ONE predatory mite racing across the underside of a bean leaf like a glossy orange-red teardrop of lacquer, its smooth pear-shaped body bearing a sparse fixed pattern of fourteen pairs of neat short bristles — far fewer than its prey carries — FOUR PAIRS of long swift legs with the hindmost pair stretched out behind like a runner's stride, a cluster of pale oval eggs laid within a colony of smaller spider mites, one newly hatched larva with only three pairs of legs nearby — absolutely NO web of silk NO wings NO antennae NO shell carapace NO long spider legs, ink stippling, no text no letters no labels",
"Tetranychus urticae":
  "antique microscope field-of-view plate: a spider-mite colony thronging the underside of a leaf in the round field, each plump oval female like a minute soft pearl of pale yellow-green bearing exactly ONE large inky blotch on EACH flank — the twin dark side-spots that give the species its name — fine transparent legs reaching ahead, a smaller diamond-shaped male skittering between them, round glassy pearl-white eggs clustered along strands of gossamer silk webbing drawn across the leaf surface — absolutely NO solid red belly NO wings NO antennae NO long spider legs NO six-legged beetle shape NO snail shell, ink stippling, no text no letters no labels",
}
