P3 = {
"Oxycomanthus japonicus":
  "antique reef plate: ONE stalkless feather crinoid perched on a sponge-encrusted stone like an upside-down bouquet of ostrich plumes, several dozen slender arms radiating from a small hidden central crown, every arm closely bordered by two neat rows of tiny feather-pinnules like the barbs of a quill, the arms banded with dark chocolate rings over warm tan, a few hook-like curling finger-cirri gripping the rock beneath the crown, a gentle drift of fine plankton dots in the water — absolutely NO central flower disc with petals NO thick snake arms NO tube feet NO long jointed stem NO fish, ink stippling, no text no letters no labels",
"Metacrinus rotundus":
  "antique deep-sea dredge plate: ONE stalked sea lily raised on a long slender stem like a chain of tiny glass beads rooted in the seabed by scattered curling hooklets, at the top a small bowl-shaped calyx from whose rim spread exactly FIVE feathered arms, each arm branching pinnately into paired plumes fringed with fine hair-like pinnules, the whole crown opened into a delicate catching-fan of pale creamy-yellow flushed apricot, one arm curled inward to show its grooved underside — absolutely NO flower petals NO green leaves NO big open flower disc NO fish fins NO jellyfish, ink stippling, no text no letters no labels",
"Amphiura vadicola":
  "antique microscope field-of-view plate: ONE tiny brittle star gliding across pale mud at the centre of the round lens field, its small smooth central disc no bigger than a peppercorn, FIVE hair-fine unbranched arms radiating outward like delicate threads of glass spaghetti, each many times longer than the disc and faintly beaded with regular joint segments, the whole body semi-translucent milky-grey with a ghost of pale brown, fine soft tentacle-feet lining the arm grooves, one arm tip cleanly broken short — absolutely NO stout spiny arms NO feathered plumes NO five thick tapering starfish arms NO crown of thorns, ink stippling, no text no letters no labels",
"Ophiothrix fragilis":
  "vintage marine tray plate: ONE common brittle star draped over a barnacled stone, its central disc rough as fine sandpaper, FIVE very long slender cord-like arms — one noticeably shorter, freshly regrown — each arm edged with neat rows of tiny paired comb-like spines like the fringe of a toothbrush, the body boldly two-toned: an orange-red disc with banded cream-and-purple arms striped like old candy sticks, tiny jaw plates visible beneath — absolutely NO thick tapering starfish arms NO suction tube feet NO feathered crown NO spines like thorns NO fish, ink stippling, no text no letters no labels",
"Diadema setosum":
  "antique tropical-reef plate: ONE long-spined sea urchin on coral rubble like a living black pincushion bristling with needles, its rounded dark test hidden beneath a dense crown of very long slender jet-black spines each longer than a hand, splayed in every direction like a hedgehog's exaggerated shadow, and at the very top of the spine ball the unmistakable ornament — a small star-like ring of five glossy blue-orange iridescent plates glowing like a tiny jewel — absolutely NO hairy fur NO octopus arms NO flower petals NO short stubby club-shaped spines NO chalk-white spines, ink stippling, no text no letters no labels",
"Echinocardium cordatum":
  "vintage seashore plate: ONE heart urchin nestled in fine damp sand in a wooden sorting tray, its delicate heart-shaped shell leaning to one side like a padded leather valentine, clothed in a dense short pelt of fine silky cream-brown spines like the nap of velvet, on its back a neat five-petalled flower traced by double rows of pore dots, a shallow furrow dipping down the front toward the buried mouth, long thread-like tube feet waving up through the sand like fishing lines — absolutely NO long black needles NO radial star shape NO five fat arms NO sharp spines, ink stippling, no text no letters no labels",
"Tripneustes gratilla":
  "antique reef-flat plate: ONE collector urchin crawling over pale coral sand, a low glossy dome like a frosted plum bun, its shell deep black-purple but densely thatched with short blunt chalk-white spines that give a sugared two-tone shimmer from a distance, a few shell fragments and algae strands riding its crown like a decorated hat, very long dark tube-feet threads reaching ahead to grip the sand, the flat pale underside turned just enough to show its neat mouth — absolutely NO long needle spines NO solid black ball NO blue-orange anal ring NO starfish arms NO octopus, ink stippling, no text no letters no labels",
"Toxopneustes pileolus":
  "vintage venomous-reef plate: ONE flower urchin resting in a still pool like a poisonous bonbon, its round test paved in soft rose, lilac and cream, decorated with stubby trumpet-shaped spines each ending in a hollow flared tip like tiny little jars, and scattered over the surface its true weapons — large three-petalled flower-like biting pincers like miniature candy tulips that open and snap shut, long translucent tube feet with round suckers feeling outward — absolutely NO long needle spines NO black pincushion ball NO starfish arms NO octopus tentacles NO fish, ink stippling, no text no letters no labels",
"Mesocentrotus nudus":
  "antique cold-water dive plate: ONE short-spined sea urchin the size of a small apple sitting on kelp-fringed rock, its strong purple-black dome armoured with stout blunt-tipped spines like a well-worn wooden mace, each spine mounted on a tiny ball joint so that some lean at odd angles, darker slender tube feet peeping far beyond the spine tips like feelers, a neat closed ring of pore plates at the apex, and beside it one urchin cracked open showing its five rich orange gonad lobes — absolutely NO chalk-white spines NO trumpet-shaped spines NO flower pincers NO extra-long black needles, ink stippling, no text no letters no labels",
"Culcita novaeguineae":
  "antique reef plate: ONE cushion star lying flat on coral pavement like a plump five-lobed dinner roll or a well-stuffed pincushion, a genuinely PENTAGONAL inflated cushion whose five arms have been reduced to nothing but soft blunt corners, its puffy upper face encrusted with low rounded knobs like the crackled crust of a baked loaf, glazed brick-orange scattered with fine white dots, the pale flat underside carrying rows of tube feet around the central mouth — absolutely NO long tapering arms NO crown of spines NO snake-like arms NO blue-purple colour NO many arms, ink stippling, no text no letters no labels",
"Choriaster granulatus":
  "vintage reef plate: ONE plump granulated sea star spread on pale sand like a giant soft sugar-cookie cut into a five-point star, its five arms short and fat with bluntly rounded tips, the whole thick body wrapped in fine blunt granular bumps like rolled dough balls, its colour warm rose-pink fading to cream on the underside, the back sprinkled with tiny dark chocolate dots, a busy fringe of tube feet just visible beneath the rounded edge — absolutely NO sharp spines NO long slim arms NO crown of thorns NO glaring red knobs NO many arms, ink stippling, no text no letters no labels",
"Archaster typicus":
  "antique sand-flat plate: ONE flat sand star half-emerged from a tray of fine quartz sand, its five slim tapering arms spread like the points of a thin cardboard star, low and flat as a biscuit, the grey-brown back marked with a lengthwise dark stripe down each arm crossed by faint darker bands, the arm rims outlined by a neat picket-fence of small rectangular marginal plates like ruler ticks, pale grooves and pointed spineless feet beneath — absolutely NO fat inflated arms NO rainbow colours NO sucker discs NO knobby spines NO many arms, ink stippling, no text no letters no labels",
"Asterina pectinifera":
  "antique tide-pool plate: ONE thick squat starfish clinging to a wet stone, a near-perfect stiff pentagon like a decorated ceramic tile with five stubby blunt arms, its deep indigo-purple back scribbled with bold irregular orange-red and yellow patches, a darker violet line running down the midline of each arm, its flat underside warm orange with neat paired rows of tube feet converging on the central mouth — absolutely NO bird of any kind NO wings NO feathers NO long tapering arms NO crown of thorns NO many arms, ink stippling, no text no letters no labels",
"Acanthaster planci":
  "antique reef plate: ONE crown-of-thorns starfish draped over a dead coral head, its body a many-spoked wheel — count the stout tapering arms radiating in all directions, from ELEVEN up to TWENTY — each arm and the small central disc densely studded with long needle-sharp venomous spines like a forest of grey-green thorns, the colours a warning mixture of purplish red, brown and olive showing between the spines, tube feet in furrows beneath — absolutely NO exactly five arms NO smooth bare skin NO short stubby cushion arms NO flower disc, ink stippling, no text no letters no labels",
"Luidia quinaria":
  "vintage dredge plate: ONE slender sand star spread on black velvet like a thin porcelain star pinched from paper, its five long arms narrow at the small central disc and gently tapering to fine sharp points, flat as a wafer, the biscuit-grey back patterned with patches of pale chalk like dried mud cracks, delicate pointed tube-foot tips lining the pale under-grooves, one arm regrowing shorter than its fellows from a clean break — absolutely NO thorn-like spines NO many arms NO thick inflated body NO bright red or blue colour NO sucker discs, ink stippling, no text no letters no labels",
"Linckia laevigata":
  "antique coral-island plate: ONE sky-blue sea star sprawled on white coral sand like a toy molded from four or five fat cylinders of bright modelling clay, its subcylindrical arms slightly tapering but ending in blunt rounded fingertip tips, the granular matte skin like fine sand dusted with pale dots, one arm shorter and regrowing from a clean break, the underside much paler cornflower blue with tiny tube feet rows — absolutely NO pointed arm tips NO red-orange colour NO long spines NO thin flat star NO many arms, ink stippling, no text no letters no labels",
"Acaudina molpadioides":
  "antique mudflat still-life: ONE burrowing sea cucumber lying on a wet dissecting tray like a fat pinkish sweet potato or a plump smooth sausage tapered toward the tail, its thin loose skin pale brick-red fading to cream at the tail, quite smooth with no spines and no rows of feet, at the blunt head end a fringe of FIFTEEN small shield-shaped tentacles like tiny flat spoons folded around the mouth, a smear of fine mud along the tray edge — absolutely NO rows of warty spikes NO branching tree-like tentacles NO plates of armour NO fish fins NO segments, ink stippling, no text no letters no labels",
"Holothuria leucospilota":
  "antique reef still-life: ONE large black sea cucumber draped over coral rubble like a thick liquorice roll of soft black rubber, plump at the rear and tapering toward the front, its whole dorsal surface studded with countless small soft warty bumps, pale tube feet set in tidy lengthwise rows on the underside, at the front end a crown of TWENTY small shield-shaped tentacles peeping from the ventral mouth, and from the rear a spray of fine white sticky threads unravelling in defence — absolutely NO spines NO shell NO fish face NO segmented worm rings NO many arms, ink stippling, no text no letters no labels",
"Holothuria nobilis":
  "vintage beche-de-mer trade plate: ONE heavy black teatfish lying on a wooden drying tray like a rolled bolster of thick black leather, extremely plump and meaty with tough hide, dark chocolate-brown to black, its back and flanks carrying distinctive large conical teat-shaped warts in loose rows like rounded upholstery studs, the paler underside crowded with tube feet, a crown of twenty shield-shaped tentacles tucked beneath the front, a cut specimen beside showing the thick wall — absolutely NO long spikes NO bright colours NO fish scales NO segmented rings NO many arms, ink stippling, no text no letters no labels",
"Holothuria scabra":
  "antique seafood still-life: ONE sandfish sea cucumber lying half-buried in a tray of fine sand like a worn old tan leather water-bag, stubby and cylindrical, its back rough with transverse wrinkles and small cone-shaped warts giving it the rasp of a file, dressed in dusty grey-brown and speckled all over with clinging grains of sand, the paler flat belly bearing dense bands of tube feet, twenty-or-so leaf-like tentacles folded at the mouth end — absolutely NO shiny black skin NO long spikes NO shell NO starfish arms NO segments, ink stippling, no text no letters no labels",
"Thelenota ananas":
  "antique South-Sea treasure plate: ONE enormous pineapple sea cucumber stretched across a long wooden tray like a giant overripe pineapple lying on its side, a full arm's length of thick soft flesh in glowing amber-orange to rust-red, its whole back covered with large fleshy warts fused at their bases into rosette clusters like pineapple scales or plum-blossom petals, tube feet packed in pale lengthwise bands on the underside, small tentacles tucked at the front end — absolutely NO hurting spines NO shell NO fish tail NO many arms NO segments, ink stippling, no text no letters no labels",
"Stichopus chloronotus":
  "vintage reef still-life: ONE stiff square-bodied sea cucumber standing in a shallow porcelain dish like a dark-green quadrangular loaf of bread, its body truly angular with almost square cross-section and blunt squared ends, the blackish bottle-green back bearing regular rows of stout cone-shaped papillae set along the corners like small rivets on a steamer trunk, the underside paler with crowded tube feet, twenty shield-shaped tentacles around the ventral mouth — absolutely NO round worm shape NO needle spines NO glowing emerald skin NO shell NO segments, ink stippling, no text no letters no labels",
}
